### PR TITLE
Improved site design using CSS and removed Submit button.

### PR DESCRIPTION
**Pull request by dollyjain51099**
I have styled the site using CSS and removed the Submit button, kindly review my code and merge it!

### CODE REVIEW

**Comment by theshubhagrwl** [comment]
> I have styled the site using CSS and removed the Submit button, kindly review my code and merge it!

Hi I have seen your changes. The styling is nice but the whole form stuff is not visible on the mobile site 😢 
Also on the desktop site the form is at an awkward position. <br>

image

**Comment by dollyjain51099** [comment]
Okay, I'll make it responsive.

**Comment by dollyjain51099** [comment]
image
I am having it displayed properly in my desktop, so should I make it responsive?

**Comment by dollyjain51099** [comment]
> > I have styled the site using CSS and removed the Submit button, kindly review my code and merge it!
> 
> Hi I have seen your changes. The styling is nice but the whole form stuff is not visible on the mobile site 😢
> Also on the desktop site the form is at an awkward position.
> 
> image

Okay, I'm working on it.

**Comment by theshubhagrwl** [comment]
Hi, please make further PR in the Dev branch. Thanks for contributing 😄

**Pull request closed without merging**
